config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  root "static_pages#landing_page"
  get "static_pages/activity"
  # get 'static_pages/landing_page'
  # get 'static_pages/privacy_policy'
  get "privacy_policy", to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    # if params[:title]
    #   @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    # else
    #   # @courses = Course.all
    #   # @q = Course.ransack(params[:q])
    #   # @courses = @q.result.includes(:user)
    # end

    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    # @courses = @ransack_courses.result.includes(:user)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    
  end

  # GET /courses/1 or /courses/1.json
  def show
    @lessons = @course.lessons
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end
  
  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price, :language, :level)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View analytics", course_path(course), { :style => "font-size: xx-small" }
      elsif course.enrollments.where(user: current_user).any?
        link_to "You bought this course. Keep learning", course_path(course), { :style => "font-size: xx-small" }
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: "btn btn-sm btn-success"
      else
        link_to "Free", new_course_enrollment_path(course), class: "btn btn-sm btn-success"
      end
    else
      link_to "Check Price", course_path(course), class: "btn btn-sm btn-success"
    end
  end
end

app/views/courses/_course.html.haml
.col-sm-12
  .card
    .card-header
      .fa.fa-graduation-cap
      = link_to course.title, course_path(course)
    .card-body
      = course.short_description
    .card-footer
      .fa.fa-tasks
      = course.lessons.count
    .card-footer
      .text-center
        = enrollment_button(course)
    .card-footer{ :style => "font-size: small" }
      .row
        .col-md-6
          .fa.fa-globe
          = course.language
        .col-md-6
          .text-end
            .fa.fa-signal
            = course.level
    .card-footer{ :style => "font-size: xx-small" }
      .row
        .col-md-4
          .far.fa-clock
          = course.created_at.strftime('%d-%b-%Y')
        .col-md-8
          .text-end
            .fa.fa-chalkboard-teacher
            = link_to course.user.username, user_path(course.user)
    - if policy(course).edit?
      .card-footer
        .text-center
          = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
          = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
  %p

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    // = f.input :language, collection: [ "English", "French", "Spanish" ], include_blank: false, include_hidden: false
    = f.input :language, collection: Course.languages, include_blank: false, include_hidden: false
    = f.input :level, collection: Course.levels, include_blank: false, include_hidden: false
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
- content_for :title do
  RGB
  \|
  Edit
  = @course.title

= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
\/
Edit
%p

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      Edit Course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', @course
    \|
    = link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do
  RGB
  \|
  All Courses

%h3
  .text-center
    Courses
    .badge.bg-info
      = @courses.count
%p

.row
  .col-sm-2
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
      = f.label :short_description
      = f.search_field :short_description_cont, placeholder: 'Short Description', class: 'form-control form-control-sm'
      = f.label :languages
      = f.select :language_cont, Course.languages, include_blank: true
      = f.label :levels
      = f.select :level_cont, Course.levels,include_blank: true
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
      = f.submit
    = link_to courses_path, class: 'btn btn-sm btn-secondary' do
      .fa.fa-sync
    %p
  .col-sm-10
    .row
      - @courses.each do |course|
        .col-sm-4
          = render 'courses/course', course: course
      != pagy_bootstrap_nav(@pagy)

app/views/courses/new.html.haml
- content_for :title do
  RGB
  \|
  Add New Course

= link_to 'Courses', courses_path
\/
New
%p

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      New course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  RGB
  \|
  = @course.title

= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p

.row
  .col-md-6
    = render 'courses/course', course: @course

  .col-md-6
    - if policy(@course).owner?
      = link_to 'Add Lesson', new_course_lesson_path(@course, @lesson), class: 'w-100 btn btn-sm btn-primary m-b-10px'
    - @lessons.each do |lesson|
      = render 'lessons/lesson', lesson: lesson