config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  root "static_pages#landing_page"
  get "static_pages/activity"
  # get 'static_pages/landing_page'
  # get 'static_pages/privacy_policy'
  get "privacy_policy", to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer.bg-secondary.text-light
  .container-fluid.text-center
    %br/
    .row
      .col-lg-4
        ©
        \#{Time.now.year}
        %br/
        = link_to t('navigation.home'), root_path, class: "#{'active font-weight-bold' if current_page?(root_path)}", style: 'color: white;'
        %br/

      .col-lg-4
        .row
        = link_to 'Teach on This Hard to Make Site', new_course_path, class: "#{'active font-weight-bold' if current_page?(new_course_path)}", style: 'color: white;'

  %br/

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand.m-l-10px{:href => "/"} Rubygems
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.me-auto
        %li.nav-item{class: "#{'active fw-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active fw-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Courses
        %li.nav-item{class: "#{'active fw-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active fw-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
        %li.nav-item{class: "#{'active fw-bold' if current_page?(enrollments_path)}"}
          = link_to enrollments_path, class: 'nav-link' do
            .fa.fa-lock-open
            Enrollments
      
      /SEARCH IN NAVBAR
      - if @ransack_courses.present?
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group
            = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search.p-t-6px{"aria-hidden" => "true"}
        // = form_tag(courses_path, method: :get) do
        //   .input-group
        //     = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        //     %span.input-group-append
        //       %button.btn.btn-primary.btn-sm{:type => "submit"}
        //         %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.me-right
        %li.nav-item{class: "#{'active fw-bold' if current_page?(static_pages_activity_path)}"}
          = link_to static_pages_activity_path, class: 'nav-link' do
            .fa.fa-bell
            Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
              
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}
    alert-dismissable fade show d-flex justify-content-between", :role => "alert"}
      = content_tag :div, msg, :id => "flash_#{name}"
      %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    // %title RubyGemsBootcamp
    %title
      = content_for?(:title) ? yield(:title) : "RubyGemsBootcamp"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br
    = render 'layouts/footer'